### ISSUE TITLE
Images are not loaded in reader mode

### ISSUE THREAD

**Issue by miduch** [prof18/feed-flow#341]
Hi, Tried FeedFlow with https://www.hs.fi/rss/tuoreimmat.xml feed and Reader mode enabled. 
It doesn't show any image in reader mode, only text displayed

**Comment by derdilla** [comment]
Similarly issue for a base64 image at https://www.stimson.org/feed/

**Comment by prof18** [comment]
It should be fixed with #540 and #537

**Comment by chinook77** [comment]
Hi, I'm having this issue with FeedFlow for Windows with https://www.statista.com/rss/

Thanks in advance.

**Comment by chinook77** [comment]
> Hi, I'm having this issue with FeedFlow for Windows with https://www.statista.com/rss/
> 
> Thanks in advance.

Any update on this? Still persist on several sites like I reported above.
Windows 11 Version 1.10.0.
On iOS works flawless.
