### ISSUE TITLE
Articles reappears after being marked as read.

### ISSUE THREAD

**Issue by chinook77** [prof18/feed-flow#817]
Hi, as the title says, I'm having this issue with read articles reappearing after feed refresh. I tested with different app settings and this behavior seems to affect feeds that aren't updated too frequently.

 It does not happen in every refresh, but after several feed refresh those old articles shows again.

<img width="1038" height="870" alt="Image" src="https://github.com/user-attachments/assets/41c5e002-bc4f-45a5-9cd1-d3c8e4ba9bb0" />

**Comment by prof18** [comment]
Fixed by https://github.com/prof18/feed-flow/pull/843

**Comment by chinook77** [comment]
Thanks for the response, but the issue persist on v 1.8.0 for Windows.

<img width="844" height="299" alt="Image" src="https://github.com/user-attachments/assets/065a70f7-5902-4682-9b2e-631b4f43dad8" />

**Comment by prof18** [comment]
Because the fix is not in 1.8 but it will be in 1.9
